version: '3.8'
services:
  boilerplate-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=toy
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - '3306:3306'
volumes:
  db:
    driver: local